name: Generate terraform-docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        config-file: .terraform-docs.yml
      
    - name: Fix permissions
      run: sudo chown runner:docker -R .git

    - name: Push changes back to PR
      run: |
        git config --local user.name github-actions[bot]
        git config user.email github-actions[bot]@noreply.github.com
        git commit -am "Updated Readme"
        git push
