name: Test Advanced Example
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: MicroK8s Action
        uses: balchua/microk8s-actions@v0.3.1
        with:
          channel: '1.25/stable'
          addons: '["dns"]'

      - name: Alias 
        run: alias kubectl='microk8s kubectl'
        
      - name: Run Terratest
        uses: cloudposse/github-action-terratest@main
        with:
          sourceDir: test
